# Generated by Django 5.0.7 on 2024-08-02 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='services',
            name='description',
            field=models.CharField(default='John', max_length=500),
        ),
        migrations.AlterField(
            model_name='services',
            name='icon',
            field=models.CharField(default='John', max_length=100),
        ),
        migrations.AlterField(
            model_name='services',
            name='name',
            field=models.CharField(default='John', max_length=100),
        ),
    ]
