# Generated by Django 5.0.7 on 2024-08-02 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_alter_services_description_alter_services_icon_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='services',
            name='description',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='services',
            name='icon',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='services',
            name='name',
            field=models.CharField(default='', max_length=100),
        ),
    ]
