# Generated by Django 5.1 on 2024-09-24 06:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='user',
            name='last_name',
        ),
    ]
