# Generated by Django 5.1 on 2024-10-08 00:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_remove_user_first_name_remove_user_last_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
